### PR TITLE
Closes #9 Support for multiple environments / engines

### LINKED ISSUE #9: Different Engines for Local / Dev / Prod
This is likely not a common issue but we have a project where we utilize multiple backend engines for our database. Locally we run postgresql and in production we utilize MSSQL. It would be really nice to be able to define different versions of SQL and have that dynamically executed in the migrate command.

### PR DESCRIPTION
**Pull request by Skylude**
WHY
------
If you have differing engines on local / dev / production you can't have different
view definitions for each engine so it could potentially try to run sqllite on a 
PostgreSQL or MSSQL database.

HOW
------
Refactor get_view_definition_from_model to always return a dictionary. Still
works with a string or callable but ultimately adds in the default engine if one
is not provided so we get a consistent definition.

Add engine parameter to both Forward and Backward ViewMigration so when
they go to run they can not run if the engine is not the proper engine.

Add engine to ViewMigration class and added protections so the migration will
only run when the view definition matches the current selected engine.

Add tests. Can be run by python django_db_views/runtests.py OR each test can be
run individually with any test runner.

Can utilize tests to add complex foward / backward migrations to test functionality
going forward.

### CODE REVIEW

**Comment by BezBartek** [comment]
Thank you!
I will try to review it today and merge

**Comment by Skylude** [comment]
I updated the README.md and version number as I forgot to do that in my last commits.

**Comment by BezBartek** [comment]
@Skylude 

Thank you for your work
I uploaded a new version on PyPI

**Comment by Skylude** [comment]
Thank you! I'm going to have a colleague begin testing with their system that utilizes multiple engines. If they / I find any bugs we'll get them submitted!

**Pull request merged**
